version: "3,7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: "elastic"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  grpc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "grpc-service"
    command: ["python", "-m", "app.servers.grpc"]
    ports:
      - 51600:51600
    environment:
      - SERVICE_GRPC_DB_ELASTICSEARCH_SCHEMA=http
      - SERVICE_GRPC_DB_ELASTICSEARCH_HOST=elasticsearch
      - SERVICE_GRPC_DB_ELASTICSEARCH_PORT=9200
      - SERVICE_GRPC_HOST=[::]
      - SERVICE_GRPC_PORT=51600
    depends_on:
      - elasticsearch

  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "graphql-service"
    command: ["python", "-m", "app.servers.graphql"]
    ports:
      - 8000:8000
    environment:
      - SERVICE_GRAPHQL_HOST=0.0.0.0
      - SERVICE_GRAPHQL_PORT=8000
      - GRPC_CLIENT_ADS_HOST=grpc-service
      - GRPC_CLIENT_ADS_PORT=51600
    depends_on:
      - grpc
