version: "3,7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  grpc:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "app.servers.grpc"]
    env_file:
      - ".env"
